version: '3'

services:
  java:
    container_name: backend-java
    env_file:
      ./api.env
    restart: always
    build: java/.
    ports:
      - "8080:8080"
    volumes:
      - ./java:/app
    networks:
      - dashboard-net

  angular:
    container_name: front-angular
    restart: always
    build: angular/.
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app
      - /app/node_modules/
    networks:
      - dashboard-net

networks:
  dashboard-net:
